from src.preprocessing.constants import (  # noqa: F401
    FAILURE_COLS, ORIG_NAMES, PALETTE, RENAME_MAP, RULE_THRESHOLDS,
    SENSOR_COLS, SENSOR_WINDOW, TYPE_MAP, WINDOW_SIZE,
)

ZSCORE_THRESHOLD    = 3.0
ROLLING_WINDOW      = 50
IF_CONTAMINATION    = 0.034
AE_PERCENTILE       = 95
AE_LATENT_DIM       = 4
FUSION_THRESHOLD    = 0.5
ML_FUSION_THRESHOLD = 0.70
FUSION_WEIGHTS      = (1/3, 1/3, 1/3)
TWF_IF_THRESHOLD    = 0.30
